version: "2"

services:
  db:
    image: couchdb:latest
    mem_limit: 128m
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    expose:
      - "5984"
    ports:
      - "5984:5984"
    networks:
      backend:
        aliases:
          - user-service-db-docker.example.com

networks:
  backend:
